"""Interface translations for SpamGuard."""

TEXT = {
    "ru": {
        "tagline": "Мультиязычная ML-демонстрация", "hero": "Проверьте сообщение<br><span>до первого клика.</span>",
        "subtitle": "Локальный анализ текста на русском, английском и испанском — без отправки сообщения во внешние сервисы.",
        "sensitivity": "Порог спама", "sensitivity_help": "Ниже порог — больше спама будет найдено, но возрастёт число ложных тревог.",
        "tabs": ["Проверить", "Пакетный анализ", "Аналитика", "Методология"], "example": "Быстрый пример",
        "placeholder": "Вставьте SMS, письмо или сообщение из мессенджера…", "analyze": "Проанализировать →",
        "privacy": "Обработка выполняется локально. Текст не покидает компьютер.", "result": "Результат анализа",
        "spam": "Высокий риск спама", "ham": "Явных признаков спама нет",
        "spam_advice": "Не отвечайте, не переходите по ссылкам и проверьте отправителя другим способом.",
        "ham_advice": "Модель считает сообщение обычным, но всё равно учитывайте контекст и отправителя.",
        "risk": "Риск спама", "detected": "Язык текста", "influence": "Фразы, повысившие оценку риска",
        "signals": "Дополнительные сигналы", "empty": "Введите сообщение или выберите пример.",
        "history": "Последние проверки", "clear": "Очистить историю", "batch_title": "Проверить сразу несколько сообщений",
        "batch_help": "Загрузите CSV/TXT до 1000 строк. Для CSV выберите столбец с текстом.", "upload": "CSV или TXT",
        "column": "Столбец с сообщением", "run_batch": "Запустить пакетный анализ", "download": "Скачать результаты CSV",
        "batch_empty": "Файл не содержит сообщений.", "found": "Обнаружено спама", "analytics_title": "Качество на отложенной выборке",
        "analytics_caption": "Дубликаты удалены до разделения данных; тестовые сообщения не использовались при обучении.",
        "matrix": "Матрица ошибок", "languages": "Метрики по языкам", "dataset": "Состав обучающих данных",
        "method_title": "Как принимается решение",
        "method_body": "Слова и символьные фрагменты преобразуются в TF-IDF-признаки. Логистическая регрессия оценивает вероятность спама, а выбранный порог превращает её в итоговую метку.",
        "limits": "Ограничения MVP",
        "limits_body": "Английская и русская части используют открытые датасеты. Испанская часть является небольшим синтетическим расширением для демонстрации. Перед реальным внедрением нужны данные из целевого канала, временное тестирование и регулярный мониторинг ошибок.",
        "sample_note": "Для быстрого запуска используется фиксированная стратифицированная выборка из 20 000 русских сообщений исходного корпуса на 66 119 строк.",
        "messages": "сообщений", "supported_languages": "Английский · Русский · Испанский",
        "model_name": "TF-IDF · Логистическая регрессия", "preview": "предварительный анализ",
        "batch_messages": "Сообщений", "metric_names": ["Общая точность", "Точность спама", "Полнота спама", "F1-мера"],
        "chart_metric_names": {"precision": "Точность", "recall": "Полнота", "f1": "F1-мера"},
        "matrix_rows": ["Факт: обычное", "Факт: спам"], "matrix_columns": ["Прогноз: обычное", "Прогноз: спам"],
        "metric_caption": "Полнота — главная ML-метрика: она показывает, какую долю реального спама обнаружила модель. Точность контролирует количество ложных тревог.",
        "method_steps": [("Сообщение", "Нормализация Unicode и удаление дубликатов"), ("TF-IDF", "Слова 1–2 грамма и символы 3–5 грамм"), ("Логистическая регрессия", "Сбалансированная и объяснимая модель"), ("Порог", "Настраиваемая граница решения")],
        "sources": "Источники: SMS Spam Collection v.1 (Almeida и Gómez Hidalgo); DmitryKRX/anti_spam_ru (Apache 2.0); синтетическое испанское расширение для учебного прототипа.",
        "language_names": {"en": "Английский", "ru": "Русский", "es": "Испанский"}, "class_names": {"ham": "Обычное", "spam": "Спам"},
        "batch_columns": {"message": "Сообщение", "language": "Язык", "spam_probability": "Вероятность спама", "prediction": "Класс"},
        "test_label": "Тест", "train_label": "Обучение",
        "feedback": "Был ли результат понятен?", "yes": "Да", "no": "Нет",
    },
    "en": {
        "tagline": "Multilingual ML demo", "hero": "Check the message<br><span>before the first click.</span>",
        "subtitle": "Local text analysis in English, Russian and Spanish — no external text processing services.",
        "sensitivity": "Spam threshold", "sensitivity_help": "A lower threshold catches more spam but may cause more false alarms.",
        "tabs": ["Check", "Batch analysis", "Analytics", "Methodology"], "example": "Quick example",
        "placeholder": "Paste an SMS, email or messenger text…", "analyze": "Analyse →",
        "privacy": "Processing is local. The text does not leave this computer.", "result": "Analysis result",
        "spam": "High spam risk", "ham": "No clear spam indicators",
        "spam_advice": "Do not reply or open links. Verify the sender through another channel.",
        "ham_advice": "The model considers this a regular message, but sender and context still matter.",
        "risk": "Spam risk", "detected": "Text language", "influence": "Phrases that increased risk",
        "signals": "Additional signals", "empty": "Enter a message or select an example.",
        "history": "Recent checks", "clear": "Clear history", "batch_title": "Check multiple messages",
        "batch_help": "Upload a CSV/TXT file with up to 1,000 rows. For CSV, select the text column.", "upload": "CSV or TXT",
        "column": "Message column", "run_batch": "Run batch analysis", "download": "Download results CSV",
        "batch_empty": "The file contains no messages.", "found": "Spam detected", "analytics_title": "Quality on the holdout set",
        "analytics_caption": "Duplicates are removed before splitting; test messages are never used for training.",
        "matrix": "Confusion matrix", "languages": "Metrics by language", "dataset": "Training data composition",
        "method_title": "How the decision is made",
        "method_body": "Word and character fragments become TF-IDF features. Logistic regression estimates spam probability and the selected threshold turns it into a label.",
        "limits": "MVP limitations",
        "limits_body": "English and Russian use open datasets. Spanish is a small synthetic extension for demonstration. Production requires data from the target channel, time-based testing and continuous error monitoring.",
        "sample_note": "Fast startup uses a fixed stratified sample of 20,000 Russian messages from the 66,119-row source corpus.",
        "messages": "messages", "supported_languages": "English · Russian · Spanish", "model_name": "TF-IDF · Logistic Regression", "preview": "on-device preview",
        "batch_messages": "Messages", "metric_names": ["Accuracy", "Spam precision", "Spam recall", "F1 score"],
        "chart_metric_names": {"precision": "Precision", "recall": "Recall", "f1": "F1 score"},
        "matrix_rows": ["Actual ham", "Actual spam"], "matrix_columns": ["Predicted ham", "Predicted spam"],
        "metric_caption": "Recall is the primary ML metric: it measures how much real spam the model detects. Precision controls unnecessary false alarms.",
        "method_steps": [("Message", "Unicode normalisation and duplicate control"), ("TF-IDF", "Word 1–2 grams and character 3–5 grams"), ("Logistic regression", "Balanced, interpretable probability model"), ("Threshold", "User-adjustable decision boundary")],
        "sources": "Sources: SMS Spam Collection v.1 (Almeida & Gómez Hidalgo); DmitryKRX/anti_spam_ru (Apache 2.0); synthetic Spanish extension for this educational prototype.",
        "language_names": {"en": "English", "ru": "Russian", "es": "Spanish"}, "class_names": {"ham": "Regular", "spam": "Spam"},
        "batch_columns": {"message": "Message", "language": "Language", "spam_probability": "Spam probability", "prediction": "Class"},
        "test_label": "Test", "train_label": "Train",
        "feedback": "Was the result clear?", "yes": "Yes", "no": "No",
    },
    "es": {
        "tagline": "Demo ML multilingüe", "hero": "Comprueba el mensaje<br><span>antes del primer clic.</span>",
        "subtitle": "Análisis local en español, ruso e inglés — sin enviar el texto a servicios externos.",
        "sensitivity": "Umbral de spam", "sensitivity_help": "Un umbral menor detecta más spam, pero puede causar más falsas alarmas.",
        "tabs": ["Comprobar", "Análisis por lotes", "Analítica", "Metodología"], "example": "Ejemplo rápido",
        "placeholder": "Pega un SMS, correo o mensaje…", "analyze": "Analizar →",
        "privacy": "El procesamiento es local. El texto no sale de este equipo.", "result": "Resultado del análisis",
        "spam": "Alto riesgo de spam", "ham": "Sin señales claras de spam",
        "spam_advice": "No respondas ni abras enlaces. Verifica al remitente por otro canal.",
        "ham_advice": "El modelo considera el mensaje normal, pero el contexto y el remitente siguen importando.",
        "risk": "Riesgo de spam", "detected": "Idioma del texto", "influence": "Frases que aumentaron el riesgo",
        "signals": "Señales adicionales", "empty": "Introduce un mensaje o selecciona un ejemplo.",
        "history": "Comprobaciones recientes", "clear": "Borrar historial", "batch_title": "Comprobar varios mensajes",
        "batch_help": "Sube un CSV/TXT de hasta 1000 filas. Para CSV, selecciona la columna de texto.", "upload": "CSV o TXT",
        "column": "Columna del mensaje", "run_batch": "Ejecutar análisis", "download": "Descargar resultados CSV",
        "batch_empty": "El archivo no contiene mensajes.", "found": "Spam detectado", "analytics_title": "Calidad en el conjunto de prueba",
        "analytics_caption": "Los duplicados se eliminan antes de dividir; los mensajes de prueba no se usan para entrenar.",
        "matrix": "Matriz de confusión", "languages": "Métricas por idioma", "dataset": "Composición de los datos",
        "method_title": "Cómo se toma la decisión",
        "method_body": "Las palabras y fragmentos de caracteres se convierten en características TF-IDF. La regresión logística estima la probabilidad y el umbral produce la etiqueta.",
        "limits": "Limitaciones del MVP",
        "limits_body": "El inglés y el ruso usan conjuntos abiertos. El español es una pequeña extensión sintética. Para producción se necesitan datos del canal objetivo, pruebas temporales y monitorización continua.",
        "sample_note": "Para un inicio rápido se usa una muestra estratificada fija de 20.000 mensajes rusos del corpus original de 66.119 filas.",
        "messages": "mensajes", "supported_languages": "Inglés · Ruso · Español", "model_name": "TF-IDF · Regresión logística", "preview": "vista previa local",
        "batch_messages": "Mensajes", "metric_names": ["Exactitud", "Precisión de spam", "Exhaustividad de spam", "Medida F1"],
        "chart_metric_names": {"precision": "Precisión", "recall": "Exhaustividad", "f1": "Medida F1"},
        "matrix_rows": ["Real: normal", "Real: spam"], "matrix_columns": ["Predicción: normal", "Predicción: spam"],
        "metric_caption": "La exhaustividad es la métrica principal: muestra cuánto spam real detecta el modelo. La precisión controla las falsas alarmas.",
        "method_steps": [("Mensaje", "Normalización Unicode y control de duplicados"), ("TF-IDF", "Palabras 1–2 gramas y caracteres 3–5 gramas"), ("Regresión logística", "Modelo equilibrado e interpretable"), ("Umbral", "Límite de decisión ajustable")],
        "sources": "Fuentes: SMS Spam Collection v.1 (Almeida y Gómez Hidalgo); DmitryKRX/anti_spam_ru (Apache 2.0); extensión española sintética para este prototipo educativo.",
        "language_names": {"en": "Inglés", "ru": "Ruso", "es": "Español"}, "class_names": {"ham": "Normal", "spam": "Spam"},
        "batch_columns": {"message": "Mensaje", "language": "Idioma", "spam_probability": "Probabilidad de spam", "prediction": "Clase"},
        "test_label": "Prueba", "train_label": "Entrenamiento",
        "feedback": "¿El resultado fue claro?", "yes": "Sí", "no": "No",
    },
}

SIGNALS = {
    "ru": {"link": "ссылка", "phone": "телефон", "money": "деньги", "urgency": "срочность", "reward": "обещание выгоды", "caps": "много заглавных", "exclamations": "давление знаками !"},
    "en": {"link": "link", "phone": "phone number", "money": "money", "urgency": "urgency", "reward": "promised reward", "caps": "excessive capitals", "exclamations": "multiple ! marks"},
    "es": {"link": "enlace", "phone": "teléfono", "money": "dinero", "urgency": "urgencia", "reward": "recompensa", "caps": "muchas mayúsculas", "exclamations": "muchos signos !"},
}
